// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package input

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}

var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}

func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}

func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}

func (FOO) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type Test_FOO2 int32

const (
	Test_Y Test_FOO2 = 17
)

var Test_FOO2_name = map[int32]string{
	17: "Y",
}

var Test_FOO2_value = map[string]int32{
	"Y": 17,
}

func (x Test_FOO2) Enum() *Test_FOO2 {
	p := new(Test_FOO2)
	*p = x
	return p
}

func (x Test_FOO2) String() string {
	return proto.EnumName(Test_FOO2_name, int32(x))
}

func (x *Test_FOO2) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Test_FOO2_value, data, "Test_FOO2")
	if err != nil {
		return err
	}
	*x = Test_FOO2(value)
	return nil
}

func (Test_FOO2) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0, 0}
}

type Test struct {
	Label     *string `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type      *int32  `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps      []int64 `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	FirstName *string `protobuf:"bytes,4,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// Types that are valid to be assigned to Union:
	//	*Test_Number
	//	*Test_Name
	Union                isTest_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

type isTest_Union interface {
	isTest_Union()
}

type Test_Number struct {
	Number int32 `protobuf:"varint,5,opt,name=number,oneof"`
}

type Test_Name struct {
	Name string `protobuf:"bytes,6,opt,name=name,oneof"`
}

func (*Test_Number) isTest_Union() {}

func (*Test_Name) isTest_Union() {}

func (m *Test) GetUnion() isTest_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Test) GetNumber() int32 {
	if x, ok := m.GetUnion().(*Test_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Test) GetName() string {
	if x, ok := m.GetUnion().(*Test_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Test) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Test_Number)(nil),
		(*Test_Name)(nil),
	}
}

func init() {
	proto.RegisterEnum("input.FOO", FOO_name, FOO_value)
	proto.RegisterEnum("input.Test_FOO2", Test_FOO2_name, Test_FOO2_value)
	proto.RegisterType((*Test)(nil), "input.Test")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xcc, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0xf1, 0x4b, 0x93, 0x9c, 0xf4, 0xa1, 0x70, 0xf7, 0x38, 0x24, 0x8b, 0x10, 0x3a, 0x05,
	0x07, 0x07, 0x97, 0x82, 0xa3, 0x43, 0xe9, 0x64, 0x20, 0x38, 0xe8, 0x24, 0x2d, 0x3c, 0xa1, 0xd0,
	0xa6, 0x21, 0x49, 0x07, 0xff, 0x2a, 0xff, 0x45, 0x69, 0xbc, 0xed, 0x7d, 0x7e, 0xf0, 0x7d, 0x00,
	0x99, 0x52, 0x7e, 0x0a, 0x71, 0xcd, 0x2b, 0xca, 0xc9, 0x87, 0x2d, 0x37, 0xbf, 0x0c, 0xc4, 0x3b,
	0xa5, 0x8c, 0x17, 0x90, 0xf3, 0x30, 0xd2, 0xac, 0x98, 0xae, 0x4c, 0xed, 0xfe, 0x81, 0xf7, 0x20,
	0xf2, 0x4f, 0x20, 0x55, 0x69, 0x66, 0xe4, 0x4b, 0xd5, 0xb6, 0xae, 0x18, 0x11, 0x44, 0xa4, 0x90,
	0x14, 0xd7, 0xdc, 0x70, 0x57, 0x6e, 0x7c, 0x00, 0xf8, 0x9e, 0x62, 0xca, 0x5f, 0x7e, 0x58, 0x48,
	0x09, 0xcd, 0x4c, 0xed, 0xea, 0xb2, 0xbc, 0x0d, 0x0b, 0xa1, 0x82, 0xa3, 0xdf, 0x96, 0x91, 0xa2,
	0x92, 0xfb, 0xb3, 0xfe, 0xe0, 0xae, 0xc6, 0x0b, 0x88, 0x92, 0x1c, 0xf7, 0xa4, 0x3f, 0xb8, 0xa2,
	0xe6, 0x0e, 0x44, 0x67, 0xed, 0x33, 0x4a, 0x60, 0x9f, 0xa7, 0xf3, 0xeb, 0x0d, 0xc8, 0xcd, 0x4f,
	0xab, 0x7f, 0xbc, 0x05, 0xde, 0x59, 0xbb, 0xcf, 0x1f, 0xa7, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x45, 0xd2, 0x93, 0xd3, 0x00, 0x00, 0x00,
}
